site_name: VocaloCafe
site_description: Amaner Potal Web
site_author: Zect
site_url: https://TeamAmaner.github.io/
repo_name: TeamAmaner/VocaloCafe
repo_url: https://github.com/TeamAmaner/TeamAmaner.github.io
google_analytics: ["Amachi", "Amaner"]

theme:
    name: material
    palette:
        scheme: preference
        primary: indigo
        accent: indigo
    font:
        text: Noto Sans
    language: ja
    logo: media/amc.png
    favicon: media/favicon.ico
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.tabs
        - navigation.indexes


markdown_extensions:
    - meta
    - codehilite:
        noclasses: true
        pygments_style: colorful
        linenums: true
    - toc:
        permalink: true
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.tabbed
    - footnotes
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.arithmatex:
        generic: true

nav:
    - ホーム: index.md
    - 派生鯖: servers.md
    - 議事録:
        - logs/index.md
        - 1: logs/1.md
        - 2: logs/2.md
        - 2.5: logs/2.5.md
    - 内輪ネタ:
        - neta.md
        - Vocaleague: Vocaleague.md
    - 歴史: history.md
    - 運営チーム: staff.md
#     - 支援に関するお願い: support.md

