site_name: VocaloCafe
site_description: Amaner Potal Web
site_author: Zect
site_url: https://teamamaner.github.io/vocalocafe/
repo_name: TeamAmaner/VocaloCafe
repo_url: https://github.com/TeamAmaner/VocaloCafe
google_analytics: ["Amachi", "Amaner"]

theme:
    name: material
    palette:
        scheme: preference
        primary: indigo
        accent: amber
    font:
        text: Noto Sans
    language: ja
    # logo: img/
    # favicon: img/
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.tabbed
    - footnotes
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.arithmatex:
        generic: true
    - meta
